[[language]]
name = "kotlin"
language-servers = ["kotlin-lsp"]

# LSP
[language-server.kotlin-lsp]
command = "kotlin-lsp"
args = ["--stdio"]

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ty", "ruff"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]
